export const WHAT_IS_FROGSMASH_CONTENT_1 = 'Have you ever asked yourself:'
export const QUOTE_1 = 'who do the people like more, a bull frog or a poison dart frog?'
export const WHAT_IS_FROGSMASH_CONTENT_1_2 = 'Or spent countless hours day-dreaming about whether a tadpole or ennui would win in a popularity contest?'
export const WHAT_IS_FROGSMASH_CONTENT_1_3 = 'Have you ever found a pebble down deep inside your pocket that you picked up last July and thought:'
export const QUOTE_2 = 'Boy, I\'m sure someone on the internet would prefer that pebble to a classic red-eyed tree frog native to the forests of Central America and north-western South America\"?'
export const WHAT_IS_FROGSMASH_CONTENT_1_4 = 'If you answered any of those questions in the affirmative, then';
export const WHAT_IS_FROGSMASH_CONTENT_1_5 = 'You\'ve come to the right place';
export const WHAT_IS_FROGSMASH_CONTENT_2 = 'FrogSmash\'s format is one as old as time itself:'
export const LIST_ITEM_1 = 'Take two competitors'
export const LIST_ITEM_2 = 'Place them side by side'
export const LIST_ITEM_3 = 'Let anonymous hordes of Internet users decide which one wins'
export const WHAT_IS_FROGSMASH_CONTENT_2_1 = 'Only, this ain\'t your grandma\'s comparison type site. We\'re not comparing people based on superficial traits like' 
export const LIST_ITEM_4 = 'Looks'
export const LIST_ITEM_5 = 'Body odour'
export const LIST_ITEM_6 = 'Bitcoin wallet'
export const NO = 'No!'
export const WHAT_IS_FROGSMASH_CONTENT_2_2 = 'We\'re not even limiting competitors to female Harvard students from the early 00s either. Instead, we\'re taking comparing apples to oranges to a whole new level. Competitors can be absolutely anything, from abstract concepts to prehistoric super-continents to skibidi rizz looksmaxxing Ohio. In FrogSmash there is only one rule:';
export const FROGSMASH_RULE_CONTENT = 'At least 50% of all competitors must be frogs.'
export const FROGSMASH_RULE_EXPLANATION_CONTENT = 'That means for every non-frog competitor that joins, the FrogSmash team will throw a new frog into the ring. So what are you waiting for? Sign up today and start smashing some froggies! And if you verify your account, you\'ll even be able to submit your own competitors to the site!';